### ISSUE TITLE
Logout loop

### ISSUE THREAD

**Issue by BurleighCharlton** [Mottokrosh/Sheet#110]
Starting at 9pm PST 2022-10-29 logging in has causes a loading page where existing characters are not available followed by a \loop back to login after about 30 seconds depending on internet speed.   
Tested on Chrome, Firefox, Edge, and with both github and google sign-ins.

**Comment by Mottokrosh** [comment]
I believe this should be fixed now. We had reached the maximum number of database connections, and restarting the app cleared up the pool.

**Comment by JadonCon04** [comment]
Resurrecting. I'm having the above issue. Also experienced by several other Campaign Companions using your character sheet. One of which posted a new issue tonight. Thanks.

**Comment by Mottokrosh** [comment]
Same issue and fix it seems. 😅
