### ISSUE TITLE
URGENT: MongoDB 3 compatibility

### ISSUE THREAD

**Issue by Mottokrosh** [Mottokrosh/Sheet#22]
On September 27, my DB host (mLab) is upgrading all their databases to version 3 at least, dropping 2.6 support. This app uses MongoSkin, which doesn't support MongoDB 3 with authentication (or at least didn't when I last checked last year).

In order for the app to continue operating after 27th September, MongoDB 3 compatibility will need to be ensured.

I am looking for volunteers to submit a PR to fix it, either by upgrading MongoSkin to a version that is compatible with Mongo 3 (if possible), or by rewriting the Mongo layer to use a different wrapper (Mongoose?) or use the native driver directly.

This is an urgent issue.

**Comment by torrentails** [comment]
From the looks of the update history [here](https://github.com/kissjs/node-mongoskin/blob/master/History.md), MongoSkin hasn't been updated to support Mongo 3 so it looks like this layer will need to be rewritten unfortunately.

**Comment by Mottokrosh** [comment]
That's what I feared. :(

**Comment by mogman1** [comment]
What are your thoughts on the native driver vs Mongoose?  I've not done JS dev before (background's in Rails and PHP), but I'm interested in trying to help out if I can.

**Comment by Mottokrosh** [comment]
Well, Mongoose requires fitting the current resources into schemas. On the other hand the native driver has a somewhat clunky API with a bunch of nesting. If it can be done without too much faff, using the native driver probably future proofs us more than using a wrapper.

**Comment by NeoEvaX** [comment]
I assume there has been no progress on this. My wife is freaking out, because she has like 20 characters saved. And your app is the only one with good notes for each item. I haven't had time to jump in and try to help. Might be easier to set up my own server to run this. Just wanted to jump in and let you know someone wants this to be fixed. I wish I knew more about angular (learning now) and MongoDB.

**Comment by Mottokrosh** [comment]
I can't promise anything, but I will try and strip out the outdated Mongoskin dependency this week and run off MongoDB native directly. It would be such a shame to see this project die an ignoble death, but it's really, really hard for me to find time to work on it.

**Comment by Mottokrosh** [comment]
🎉 🎈 🍰 

Alright, I have just pushed an update that removes the stale Mongoskin, and replaces it with Monk, which is being actively developed. The syntax changes were not excessive, though I did have to rewrite all the database queries slightly. I didn't go for the native driver in the end, as there were questions about connection management that I couldn't find the answers for easily.

I have tested all the new database interactions locally, and briefly on the live server, and it all worked fine for me, but I would really appreciate if you guys could check on your ends too. If all went well, you should see absolutely no difference.

My MongoDB provider (mLab) is switching all the databases over over a 4 period window from September 27. During this time they say there be one outage of less than 5 minutes. Fingers crossed!

Long live Mottokrosh's Eldritch Online Character Sheet! (Hopefully!)

**Comment by NeoEvaX** [comment]
Code change on the current live site, or do you need us to test our own deployment of your code?

**Comment by Mottokrosh** [comment]
On the current live site!





On Tue, Sep 20, 2016 at 8:37 PM +0100, "NeoEvaX" <notifications@github.com> wrote:












Code change on the current live site, or do you need us to test our own deployment of your code?
