### ISSUE TITLE
Contributors wanted

### ISSUE THREAD

**Issue by Mottokrosh** [Mottokrosh/Sheet#26]
As you all know I've not had any real time to spend on this project besides keeping it alive by paying the bills and doing emergency database work, so I'd really love it if one or more intrepid Pathfinder fans and developers wanted to take a stab at tackling some of the issues and feature requests currently listed.

NodeJS and AngularJS experience would be very helpful, but any JavaScript skills should do.

**Comment by Rio** [comment]
I think I'm up for it. Just started GMing with a small group of friends and one of them found this project and everyone is impressed. My main experience is backend in python, go and rust but have done a project or two in node.

As a GM I'm running into some trouble handling tracking combat so i'm interested in how we could build on this to help out in GMing.

I'm actually running session 0 for Crypt of the Everflame right now but after that I'm going to try to containerize this and add a `docker-compose.yml` just to get a feel for the project.

**Comment by Mottokrosh** [comment]
Sounds great. Let me know if you need any help with the setup!

Frank.

**Comment by Rio** [comment]
Finally got around to working on it, but man I never realized package management in js could be such a mess. Those two projects I did didn't have as many dependencies as this has. Also Angular is a real mystery for me. Hoped that there was more logic in the backend to work on but seems as if it's just there as a thin layer to auth and the database.

Any way I'll just be prodding away. Trying to get it all running at least but I'm not making any promises.
Still loving the project though. My players as well!

**Comment by Mottokrosh** [comment]
Yes, Angular and Grunt were all the rage back in the day when I started this. :)
