### ISSUE TITLE
Consider porting app to Vue

### ISSUE THREAD

**Issue by Mottokrosh** [Mottokrosh/Sheet#37]
This would leave the thin Node backend largely untouched, and impact only the Angular part.

Vue is a better, modern framework than the by now outdated Angular 1, with an active and engaged community.

**Comment by tahege** [comment]
While I agree the app should be updated from Angular 1, why make the jump to Vue? I understand Vue is fairly thin, I'm just curious why it vs using a newer version of Angular or some other modern framework?

**Comment by Mottokrosh** [comment]
Fair question. While I'm not averse to someone jumping in with another framework, as long as they're willing to put the effort in, both myself and another community member are very excited to work with Vue. I have written all my other recent RPG apps in it, and use it in my daily work too. In my opinion it's the best Javascript framework out there at the moment - but maybe something will come along to unseat it at some point. :)

**Comment by tahege** [comment]
That makes sense. In my experience Vue was something I got a chance to use when it was first coming out, but then quickly got eclipsed by Angular 2 and React by other job opportunities in the area. I've never found one framework to be _the best_, but rather some better than others in certain apps and situations; so maybe I'll take this opportunity to refresh myself on Vue. :)

Also I agree, Angular is a beast. I've done several Angular 1 to 2 rewrites and the only thing that makes is easier is experience doing it. While I like it for smaller apps, it can be too easy to mess up and become frustrated which I think makes it less ideal for open source projects. Also you're correct, currently on Angular 5 with 6 coming this year.
