### ISSUE TITLE
Spells from "Pathfinder Player Companion: Arcane Anthology" are not in database

### ISSUE THREAD

**Issue by Tropingenie** [Mottokrosh/Sheet#42]
Hello,

I was recently levelling up my Magus, and wanted to take the _[Force Sword](https://www.d20pfsrd.com/magic/all-spells/f/force-sword)_ spell. However, when I entered it in, the spell did not appear. Fortunately, I have access to a copy of the [Arcane Anthology](http://paizo.com/products/btpy9i8l?Pathfinder-Player-Companion-Arcane-Anthology), the book that spell is from, and started trying other spells from that book. None of the ones I tried appeared, and thus I figured that the book simply wasn't in the database.

Thanks for your time,

Jeb

**Comment by JaredClayborn** [comment]
These appear to be there now.  I'm going to close this, let me know if you have any issues
