### ISSUE TITLE
Issue with attempting to make changes to a sheet, only to be signed out again.

### ISSUE THREAD

**Issue by sickle92** [Mottokrosh/Sheet#64]
Whenever me or my players have to make a change to our sheets, we are automatically signed out. We expect this, but logging back in through google authentication to make changes only prompts for a login request again, without making any changes to the sheet.

**Comment by dndoutlaw** [comment]
Same here, which sucks because my group made plans to play tonight

**Comment by NicholasClinton** [comment]
I've been having the same issue for about a day and a half. I sign in using my Google account though

**Comment by JaredClayborn** [comment]
Hello folks.  I deployed a change yesterday and didn't see this problem.  My apologies.  I've re-released the older version and that appears to have fixed the issue.  If you see any other issues, please let me know.  I'll continue to monitor the situation and I'll take a more critical look at the code I released to see what caused the issue.  Again, very sorry.
