### ISSUE TITLE
Unsafe website error

### ISSUE THREAD

**Issue by Audinissa** [Mottokrosh/Sheet#68]
I get a google page that tells me to "return to safety" because there is something wrong with the page. I also get 404 and 503 errors.
![image](https://user-images.githubusercontent.com/70502458/91684525-aa72b300-eb0c-11ea-9bb8-bb6da0e83d32.png)

**Comment by LikeLakers2** [comment]
I believe this is related to #67.

I highly recommend that you wait for the issue to be taken care of. **Do not proceed to the website when you get this error.**

**Comment by Mottokrosh** [comment]
Yes, this is almost certainly related to #67.

**Comment by Mottokrosh** [comment]
This is also now fixed as part of #67 .
