### ISSUE TITLE
Unable to login via Github

### ISSUE THREAD

**Issue by AndrewSkinner** [Mottokrosh/Sheet#80]
<img width="1177" alt="Screen Shot 2021-05-05 at 12 16 12 PM" src="https://user-images.githubusercontent.com/16245890/117182212-b0a3e800-ad9b-11eb-8340-04d4a050e86a.png">
This is what I get when trying to login via github.

Not sure what's happening here, but I love this tool and use it for all of my character sheets.

**Comment by Mottokrosh** [comment]
Fixed by https://github.com/Mottokrosh/Sheet/pull/88
