### ISSUE TITLE
New GitHub login doesn't restore old characters

### ISSUE THREAD

**Issue by maxluoXIII** [Mottokrosh/Sheet#89]
Apologies, seems that my PR #88 doesn't fully fix the issue in #87. The previous characters I had don't show up when logging in with Github. 

I suspect that the new authentication method creates a new user id instead of using the old one. 

Not sure if there's a way to get around this other than query based on username/profile url rather than id?

**Comment by Mottokrosh** [comment]
Can confirm that the fix shows characters I had added before and after the Github auth change!
