### ISSUE TITLE
Google Authorization Error

### ISSUE THREAD

**Issue by PyrdiuLefquo** [Mottokrosh/Sheet#94]
The error has been resolved, but I'm still logging it for you.
![Mottokrosh](https://user-images.githubusercontent.com/93744499/140432051-52f64f9c-a8b1-4952-b297-728568501d61.jpg)

Edit ( 7:21/19:21PST): Error is back. I thought it was resolved but apparently not. My fault for prematurely saying so.

**Comment by lokithunderson** [comment]
I'm having the same issue

![image](https://user-images.githubusercontent.com/93723696/140434059-512373c8-91d4-4165-a60b-fddebe0615cb.png)

**Comment by thegreatfrog05** [comment]
Same issue here. How did you resolve?

**Comment by PyrdiuLefquo** [comment]
Honestly, it resolved itself. I thought it was Mottokrosh that did it.

**Comment by maxluoXIII** [comment]
Thanks for reporting this, I'm able to replicate and am looking into it.

**Comment by maxluoXIII** [comment]
If you're having issues, try using https. (If you see the url prefixed with "http", add an "s" after it. Chromium browsers removed that for some reason, so add the "https://" yourself.)

**Comment by thegreatfrog05** [comment]
That worked. Thanks so much!

**Comment by Precentor-Van-Zandt** [comment]
Google Authorization Error
Error 400: invalid_request

**Comment by maxluoXIII** [comment]
@Precentor-Van-Zandt Please see my previous comment:

> If you're having issues, try using https. (If you see the url prefixed with "http", add an "s" after it. Chromium browsers removed that for some reason, so add the "https://" yourself.)
