### ISSUE TITLE
Google Authorization Error

### ISSUE THREAD

**Issue by pennilessrogue** [Mottokrosh/Sheet#95]
![ABC707A1-AE53-4610-8BA9-1C8E2CE296BC](https://user-images.githubusercontent.com/94094245/141232394-6fda4b63-7452-4c06-91b6-b0caa6291494.png)
Cannot access any saved character sheets, will not allow me to sign in via Google account and I have no alternative way to sign in to access this

**Comment by maxluoXIII** [comment]
Please see #94 .
